# 保存和恢复

tf.train.Saver 类提供了保存和恢复模型的方法。通过 tf.saved_model.simple_save 函数可轻松地保存适合投入使用的模型。 Estimator 会自动保存和恢复 model_dir 中的变量。

## 保存和恢复变量

Tensorflow变量是表示由程序操作的共享持久状态的最佳方法。tf.train.Saver构造函数正对途中所有变量或指定列表的变量将save和restore操作添加到图中。Saver对象提供了运行这些操作的方法，并指定写入或读取该检查点文件的路径。

### 保存变量

使用tf.train.Saver()创建Saver来管理模型中的所有变量。

In [1]:
import tensorflow as tf
#Create some variable
v1 = tf.get_variable("v1",shape=[3],initializer=tf.zeros_initializer())
v2 = tf.get_variable("v2",shape=[5],initializer=tf.zeros_initializer())

inc_v1 = v1.assign(v1+1)
dec_v2 = v2.assign(v2-1)

#Add an op to initialize the variables.
init_op = tf.global_variables_initializer()

#Add an op tosave and restore allthe variables.
saver = tf.train.Saver()

#Later,luanch the model,initialize the variable,do some work,and save the variable to disk.
with tf.Session() as sess:
    sess.run(init_op)
    #Do some work with the model.
    inc_v1.op.run()
    dec_v2.op.run()
    #Save the variable to disk.
    save_path = saver.save(sess,"/tmp/model.ckpt")
    print("Model saved in path : %s" %save_path)

D:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Model saved in path : /tmp/model.ckpt


### 恢复变量

tf.train.Saver对象不仅将变量保存到检查点文件中，还将恢复变量。请注意，当您恢复变量时，不必事先将其初始化。

In [2]:
tf.reset_default_graph()

#Create some variables.
v1 = tf.get_variable("v1",shape=[3])
v2 = tf.get_variable("v2",shape=[5])

#Add ops to save and restore all the variables.
saver = tf.train.Saver()

#Later,Launch the model ,use the saver to restore variables from disk and do some work with the model .
with tf.Session() as sess:
    #Restore variables from disk.
    saver.restore(sess,"/tmp/model.ckpt")
    print("Model restored.")
    #Check the value of the variables
    print("v1 : %s" % v1.eval())
    print("v2 : %s" % v2.eval())

INFO:tensorflow:Restoring parameters from /tmp/model.ckpt
Model restored.
v1 : [1. 1. 1.]
v2 : [-1. -1. -1. -1. -1.]


### 选择要保存和恢复的变量

In [3]:
tf.reset_default_graph()
#Create some variables.
v1 = tf.get_variable("v1",[3],initializer=tf.zeros_initializer())
v2 = tf.get_variable("v2",[5],initializer=tf.zeros_initializer())

#Add ops to save and restore only 've' using the name "v2"
saver = tf.train.Saver({"v2":v2})

#Use the saver object normally after that.
with tf.Session() as sess:
    #Initialize v1 since the saver will not
    v1.initializer.run()
    saver.restore(sess,"/tmp/model.ckpt")
    
    print("v1 : %s" % v1.eval())
    print("v2 : %s" % v2.eval())


INFO:tensorflow:Restoring parameters from /tmp/model.ckpt
v1 : [0. 0. 0.]
v2 : [-1. -1. -1. -1. -1.]


### 检查某个检查点中的变量

我们可以使用 inspect_checkpoint 库快速检查某个检查点中的变量。

In [9]:
#import the inspect_checkpoint library
from tensorflow.python.tools import inspect_checkpoint as chkp

#print all tensor in checkpoint file
chkp.print_tensors_in_checkpoint_file("/tmp/model.ckpt",tensor_name='',all_tensors=True)

# tensor_name:  v1
# [ 1.  1.  1.]
# tensor_name:  v2
# [-1. -1. -1. -1. -1.]

#print only tensor v1 in checkpoint file
chkp.print_tensors_in_checkpoint_file('/tmp/model.ckpt',tensor_name='v1',all_tensors=False)

# tensor_name:  v1
# [ 1.  1.  1.]

#print only tensor v in checkpoint file
chkp.print_tensors_in_checkpoint_file("/tmp/model.ckpt",tensor_name="v2",all_tensors=False)

# tensor_name:  v2
# [-1. -1. -1. -1. -1.]

tensor_name:  v1
[1. 1. 1.]
tensor_name:  v2
[-1. -1. -1. -1. -1.]
tensor_name:  v1
[1. 1. 1.]
tensor_name:  v2
[-1. -1. -1. -1. -1.]


## 保存和恢复模型

使用 SavedModel 保存和加载模型 - 变量、图和图的元数据。SavedModel 是一种独立于语言且可恢复的神秘序列化格式，使较高级别的系统和工具可以创建、使用和转换 TensorFlow 模型。

## 构建和加载 SavedModel

### 简单保存

创建 SavedModel 的最简单方法是使用 tf.saved_model.simple_save 函数：

### 手动构建 SavedModel

使用 SavedModelBuilder 构建 SavedModel 的典型方法

### 加载 Python 版 SavedModel

### 加载 C++ 版 SavedModel

### 在 TensorFlow Serving 中加载和提供 SavedModel

In [ ]:
imp